version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ServerMateo1/
permissions:
  - object: /home/ec2-user/myapp
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
